name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Cache Plugin Verifier IDEs
      uses: actions/cache@v2
      with:
        path: ~/.pluginVerifier
        key: ${{ runner.os }}-${{ hashFiles('**') }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and verify plugin
      run: ./gradlew --no-daemon build runPluginVerifier -DIDEA_VER=212
    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: build/reports/
    - name: Upload distribution
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: build/distributions/*.zip
